"use client";
import type { UpgradeReport } from "@/lib/types";
import { XCircle, AlertTriangle, MessagesSquare } from "lucide-react";

export function UpgradeReportView({ report }: { report: UpgradeReport }) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
      <div className="space-y-3">
        <KV label="Package version" value={report.packageVersion} />
        <KV label="Webhook status" value={report.webhookStatus} />
        <KV label="Scheduled jobs" value={report.scheduledJobs} />
        <KV label="Page layouts" value={report.pageLayoutStatus} />
        <KV label="Completion time" value={`${report.completionTimeMinutes} min`} />
        <KV label="Generated by" value={report.generatedBy} />
      </div>
      <div className="space-y-3">
        {report.warnings.length > 0 && (
          <div>
            <div className="text-[10px] uppercase font-bold text-slate-500 tracking-wider mb-1.5 flex items-center gap-1.5">
              <AlertTriangle size={11} className="text-amber-500" /> Warnings
            </div>
            <ul className="space-y-1.5">
              {report.warnings.map((w, i) => (
                <li key={i} className="text-[11.5px] text-amber-800 flex gap-1.5 leading-relaxed">
                  <span className="shrink-0 text-amber-500">▸</span>
                  <span>{w}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        {report.issuesFound.length > 0 && (
          <div>
            <div className="text-[10px] uppercase font-bold text-slate-500 tracking-wider mb-1.5 flex items-center gap-1.5">
              <XCircle size={11} className="text-rose-500" /> Issues found
            </div>
            <ul className="space-y-1.5">
              {report.issuesFound.map((w, i) => (
                <li key={i} className="text-[11.5px] text-rose-700 flex gap-1.5 leading-relaxed">
                  <span className="shrink-0 text-rose-500">▸</span>
                  <span>{w}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        {report.engineerNotes.length > 0 && (
          <div>
            <div className="text-[10px] uppercase font-bold text-slate-500 tracking-wider mb-1.5 flex items-center gap-1.5">
              <MessagesSquare size={11} className="text-indigo-500" /> Engineer notes
            </div>
            <ul className="space-y-1.5">
              {report.engineerNotes.map((w, i) => (
                <li key={i} className="text-[11.5px] text-slate-700 leading-relaxed p-2.5 rounded-lg bg-slate-50 border border-slate-100">
                  {w}
                </li>
              ))}
            </ul>
          </div>
        )}
        {report.warnings.length === 0 && report.issuesFound.length === 0 && report.engineerNotes.length === 0 && (
          <div className="text-[12px] text-slate-500 border-2 border-dashed border-slate-200 rounded-xl p-4 text-center">
            No warnings, issues, or engineer notes.
          </div>
        )}
      </div>
    </div>
  );
}

function KV({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start gap-3">
      <div className="text-[10px] uppercase font-bold text-slate-500 tracking-wider w-32 shrink-0 pt-1">{label}</div>
      <div className="text-[12.5px] text-slate-800 leading-relaxed">{value}</div>
    </div>
  );
}
